## 실제 데이터 연습

In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('filtered_channel.csv', index_col='channel_id')
df

,subscribers,avg_views_sub,avg_30days_view,week_upload
channel_id,,,,
UC--Vjom9AbabcCMzRLRo0vQ,23500,3.336610,42323.00,0.144231
UC-0229MiVYnQoUxdLJnFl_g,111000,0.944272,5647.50,0.401130
UC-0JYXUFvDy2wlrBXazqz0w,19900,0.526456,10126.60,0.804651
UC-0tICWyA0_AJAVMBHL8GdQ,187000,1.197713,205046.00,1.467740
UC-1OBOWjQTHpkWhvgPAo1Fg,6530,1.033556,1799.60,0.830137
...,...,...,...,...
UCzzsPLVj67qyXrVcGmewSmg,20600,11.910761,48464.50,0.854430
UCzzt6bFEBcy-CoZeFvTSq0A,41700,0.638564,29192.80,2.100360
UCzzt9YrAmPsya3zBMmS9Nmw,20900,1.357863,18890.30,0.876972
UCzztPvTc6mfxKji1AkyROgw,14500,0.397218,5759.67,2.314290
UCzztzqBv_dJjo9MV4yhiAAw,86192,3.200005,2335.00,0.019763

In [40]:
df.describe()

        subscribers  avg_views_sub  avg_30days_view   week_upload
count  1.785400e+04   17854.000000     1.785400e+04  17854.000000
mean   9.026482e+04       1.394733     6.010108e+04      1.195469
std    6.494410e+05       1.768638     3.219756e+05      1.814224
min    3.910000e+03       0.200000     6.000000e+00      0.006787
25%    7.750000e+03       0.384455     2.295443e+03      0.328744
50%    1.730000e+04       0.734108     8.592060e+03      0.681650
75%    5.780000e+04       1.575464     3.896635e+04      1.363640
max    6.850000e+07      11.989538     3.054530e+07     41.053400

In [8]:
df['week_upload'].describe()

count    17854.000000
mean         1.195469
std          1.814224
min          0.006787
25%          0.328744
50%          0.681650
75%          1.363640
max         41.053400
Name: week_upload, dtype: float64

In [11]:
df.loc[['UC--Vjom9AbabcCMzRLRo0vQ', 'UC-1OBOWjQTHpkWhvgPAo1Fg'],['subscribers', 'week_upload']]

                          subscribers  week_upload
channel_id
UC--Vjom9AbabcCMzRLRo0vQ        23500     0.144231
UC-1OBOWjQTHpkWhvgPAo1Fg         6530     0.830137

In [39]:
df.iloc[1:3, 3]

channel_id
UC-0229MiVYnQoUxdLJnFl_g    0.401130
UC-0JYXUFvDy2wlrBXazqz0w    0.804651
Name: week_upload, dtype: float64

In [56]:
df_week_upload = df.loc[df['week_upload']>=7, ['subscribers', 'week_upload']]
df_week_upload

                          subscribers  week_upload
channel_id
UC-Dc0VZKrrujtSzea9Xd9eA        11800      7.18644
UC-Zedn7a_RJyb5hUQ-aGZog       866000     26.40180
UC-rWRU8Lp9g0bmO9LjKRJNQ        13100      7.90426
UC0M-_02RJqMlGTKUjF1WhJg       717000     17.44070
UC0aKwoKNeqBaUwiEXmkQaGQ       290000     12.48940
...                               ...          ...
UCywEN4WQwaqkI642yymZhEg        22100      7.08333
UCzHCojF0brodPKPs-s5_sxQ        18300      7.94737
UCzSlNLuTKagxbM-91DMIY_g         5620     25.27270
UCzlwvfQeKPhODjgc2ZJU9dA        42200      8.02128
UCzmA_AtyC8OVZx1TrTwaALw        22000      9.60000

[253 rows x 2 columns]

In [57]:
df_week_upload.sort_values('week_upload', ascending = False)

                          subscribers  week_upload
channel_id
UCCW7N13hV53wZ3ufTFtkmhA         9920     41.05340
UCOZzNsrNCA_Ve5rtGbwzeJw        10900     36.00000
UCfA0tTDLNooBB0ymdoI5M7w       157000     33.38510
UCkRTpJ1Nl0xv291dmtqYQrg         7740     33.21430
UCVPLC5i71hZhced5r1FelIQ         4800     27.86960
...                               ...          ...
UCE32_bgNTs2Rgy_RLpfHJaQ        17329      7.07190
UCXiKP3OgP2hBoY6X2PW44FA         4620      7.06522
UCecs6KE0m_mxRp-DSZpwYTg         4350      7.03636
UC9Amgn24YSvlyzKWynKZh-w       261000      7.01370
UC3v_I1bVnV0F8ohePlNpNhw         4170      7.00000

[253 rows x 2 columns]